// routes/read/[slug].tsx
/** @jsx h */
import { h } from "preact";
import { PageProps, Handlers } from "$fresh/server.ts";
import { HomeLayout } from "../../components/HomeLayout.tsx";
import { PostProps, SettingsProps } from "../../utils/types.ts";

interface GhostData {
  posts: Array<PostProps>;
  settings: SettingsProps;
}

const formatter = new Intl.DateTimeFormat('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric'
});

export const handler: Handlers<GhostData> = {
  async GET(req, ctx) {
    const API_URL = Deno.env.get("IMK_API_URL");
    const API_KEY = Deno.env.get("IMK_API_KEY");
    const API_VERSION = "v4";
    const postFetch = await fetch(`${API_URL}/ghost/api/content/posts/slug/${ctx.params.slug}?key=${API_KEY}&include=tags,authors&limit=1`);
    const postData = await postFetch.json();
    const settingsFetch = await fetch( `${API_URL}/ghost/api/content/settings/?key=${API_KEY}`);
    const settingsData = await settingsFetch.json();

    return ctx.render({...postData, ...settingsData});
  },
};

export default function SinglePost(props: PageProps<GhostData>) {
  const post = props.data.posts[0]
  const date = new Date(post.published_at);
  const updatedDate = (post.updated_at !== post.published_at) && new Date(post.updated_at!);

  return (
    <HomeLayout title={`${post.title} | ${props.data.settings.title}`}
      nav={props.data.settings.secondary_navigation}
      description={post.excerpt}
      twitterImage={post.twitter_image || post.feature_image}
      fbImage={post.og_image || post.feature_image}
      url={post.canonical_url} >
      <div class="content single-post">
        <h1 class="title">{post.title}</h1>
        <div class="metadata">
          <span class="date">Published: {formatter.format(date)}</span>
          {updatedDate && <span class="updated">Updated: {formatter.format(updatedDate)}</span>}
          <span><a href={post.primary_author!.website} target="_blank">{post.primary_author!.name}</a></span>
        </div>
        <div class="post-data" dangerouslySetInnerHTML={{ __html: post.html! }}></div>
      </div>
    </HomeLayout>
  );
}

// src/routes/read/[slug]/+page.svelte
<script>
    import Header from "$lib/components/Header.svelte";
    import Footer from "$lib/components/Footer.svelte";
    import { base } from "$app/paths"

    let { data } = $props();

    const formatter = new Intl.DateTimeFormat('en-US', {
        month: 'long',
        day: 'numeric',
        year: 'numeric'
    });

    const post = data.posts[0]
    const date = new Date(post.published_at);
    const updatedDate = (post.updated_at !== post.published_at) && new Date(post.updated_at);
</script>

<svelte:head>
    <meta name="description" content={post.excerpt || ''} />
    <meta property="og:url" content={post.canonical_url || data.url} />
    <meta property="og:type" content="article" />
    <meta property="og:title" content={post.title} />
    <meta property="og:description" content={post.excerpt || ''} />
    <meta property="og:image" content={post.og_image || post.feature_image || data.settings.og_image} />
    <meta property="twitter:card" content="summary_large_image" />
    <meta property="twitter:url" content={post.canonical_url || data.url} />
    <meta property="twitter:title" content={post.title} />
    <meta property="twitter:description" content={post.excerpt || ''} />
    <meta property="twitter:image" content={post.twitter_image || post.feature_image || data.settings.twitter_image} />
    <title>{post.title}</title>
    <link rel="stylesheet" href="{base}/prism.css" />
    <script defer src="{base}/prism.js" data-website-id="730c6c26-d1f9-4e0b-8f78-26c37ce5093e"></script>
</svelte:head>


<Header urls={data.settings.navigation}></Header>
<div class="content single-post">
    <h1 class="title">{post.title}</h1>
    <div class="metadata">
        <span class="date">Published: {formatter.format(date)}</span>
        {#if updatedDate}
            <span class="updated">Updated: {formatter.format(updatedDate)}</span>
        {/if}
        <span><a href={post.primary_author.website} target="_blank">{post.primary_author.name}</a></span>
    </div>
    <div class="post-data">{@html post.html}</div>
</div>
<Footer urls={data.settings.secondary_navigation}></Footer>

<style>
    .title {
        font-size: 2.8rem;
        font-weight: bold;
        grid-area: title;
    }

    .content {
        grid-area: content;
        display: grid;
        grid-template-areas:
            '. title .'
            '. posts .';
        grid-template-columns: 1fr minmax(450px, 50vw) 1fr;
        grid-template-rows: 5rem auto;
    }

    .content {
        display: grid;
        grid-template-areas:
            'title'
            'metadata'
            'post';
        grid-template-columns: minmax(100px, 2fr);
        grid-template-rows: fit-content(50%) fit-content(1rem) auto;
        grid-row-gap: 2rem;
    }

    .title {
        font-size: 2.8rem;
        font-weight: bold;
        grid-area: title;
    }

    .metadata {
        grid-area: metadata;
        opacity: .8;
        color: #454545;
        font-size: 1.2rem;
        padding-bottom: 1rem;
        border-bottom: 1px dotted #32323230;
        display: grid;
        grid-row-gap: .2em;
    }

    .metadata .updated {
        font-style: italic;
    }

    .metadata span {
        line-height: 1;
    }

    .metadata span a {
        color: inherit;
        text-decoration: inherit;
        transition: .2s color ease-out;
    }

    .metadata span a:hover {
        color: var(--green);
    }

    .post-data {
        grid-area: post;
    }

</style>
